# Generated by Django 2.2.24 on 2021-08-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimizationitemresults',
            old_name='forecast_period',
            new_name='period',
        ),
    ]
