# Generated by Django 2.2.24 on 2021-08-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210812_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationitemresults',
            name='period',
        ),
        migrations.AddField(
            model_name='optimizationitemresults',
            name='supplier_id',
            field=models.ForeignKey(db_column='supplier_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='items.SupplierDetail', verbose_name='Προμηθευτής'),
            preserve_default=False,
        ),
    ]
